### ISSUE TITLE
Some error occurred while executing silicon

### ISSUE THREAD

**Issue by aslak01** [NarutoXY/silicon.lua#1]
It's not working for me, I get the error message "Some error occurred while executing silicon".

I'm using astrovim, and my config for silicon.lua is here: https://github.com/aslak01/astrovim-settings/blob/master/init.lua (lines 191-193 and 229-233.

**Comment by NarutoXY** [comment]
Did you install silicon?

**Comment by aslak01** [comment]
Yes

**Comment by NarutoXY** [comment]
- Fork the repo
- Go to lua/silicon/requests.lua
- Uncomment the commented debug lines
- :PackerSync

**Comment by NarutoXY** [comment]
I'll add a debug flag tomorrow.

Can you try running silicon manually?

**Comment by aslak01** [comment]
It runs as expected, I assume. As in it errors out with a bunch of flags I was supposed to set when I call it.

**Comment by NarutoXY** [comment]
@aslak01 check with https://github.com/NarutoXY/silicon.lua/commit/72b51baebaf945ae381e8565444ebe1c87e53a6f

Basically I added a new debug flag. Please send the log printed.
```vim
:lua require("silicon").visualise_api({debug = true})
:messages
```

**Comment by aslak01** [comment]
Missing font:
```
"[error] Error occurs when load font `monospace`: Font error: no font found"
"thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/font.rs:211:14"
"note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"
```

I'll see if I can fix it by setting a font I have available in config.

**Comment by aslak01** [comment]
Seems like setting the font locally didn't help, still get the same error.

```
      { "narutoxy/silicon.lua", requires = "nvim-lua/plenary.nvim",
        config = function()
          require("silicon").setup({
            font = "JetBrainsMono Nerd Font"
          })
        end
      }
```

**Comment by NarutoXY** [comment]
Hmm strange, try using other fonts

PS: Font needs to be locally installed.

**Comment by aslak01** [comment]
I would recommend tho, to either put a more descriptive error message on a font error, or use a default setting that would natively work cross platform. Not that I know what that setting would be.

**Comment by NarutoXY** [comment]
> I would recommend tho, to either put a more descriptive error message on a font error, or use a default setting that would natively work cross platform. Not that I know what that setting would be.

`monospace` was supposed to work on all platforms. Btw on which platform are you on? I can prompt user to explicitly mention the font before using the plug-in.

**Comment by aslak01** [comment]
I'm on macOS
