### ISSUE TITLE
Error running silicon

### ISSUE THREAD

**Issue by chewbakartik** [NarutoXY/silicon.lua#10]
Hey this plugin looks awesome, I was trying to get it setup for myself (nvim 0.8) but ran into an error.

```
E5108: Error executing lua .../site/pack/packer/start/silicon.lua/lua/silicon/init.lua:37: loop or previous error loading module 'silicon.request'
stack traceback:
        [C]: in function 'require'
        .../site/pack/packer/start/silicon.lua/lua/silicon/init.lua:37: in function 'visualise_api'
        [string ":lua"]:1: in main chunk
```

I've kept the setup pretty simple, just following the default settings:

`	use { "narutoxy/silicon.lua", requires = { "nvim-lua/plenary.nvim" }, config = function() require('silicon').setup({}) end }`

I'll keep digging but wanted to make this issue in case it's something that anyone else has run into.

**Comment by NarutoXY** [comment]
Whats the OS? Check #1 in case of macOS

**Comment by chewbakartik** [comment]
I use arch, btw. Sorry, meant to add that in the original post. Neovim was installed manually from compiling the release-0.8 branch. Happy to try assisting in debugging this any way that you need.

**Comment by NarutoXY** [comment]
Maybe try doing with `{debug = true}` and send the log

**Comment by chewbakartik** [comment]
So I added the font to the config, and the error message has changed slightly. The debug flag doesn't add anything else to the `:messages` output.
```
E5108: Error executing lua ...te/pack/packer/start/silicon.lua/lua/silicon/request.lua:23: attempt to concatenate local 'config_dir' (a nil value)
stack traceback:
        ...te/pack/packer/start/silicon.lua/lua/silicon/request.lua:23: in main chunk
        [C]: in function 'require'
        .../site/pack/packer/start/silicon.lua/lua/silicon/init.lua:37: in function 'visualise_api'
        [string ":lua"]:1: in main chunk
```

**Comment by NarutoXY** [comment]
Whats the result of `silicon --config-file`

**Comment by chewbakartik** [comment]
Well, that will do it. I never had silicon installed on my machine. I jumped straight to the installation section of the readme with just a cursory glance at the requirements. I totally missed that I needed to install something else. Closing this ticket, thanks again for this and your prompt responses.
