### ISSUE TITLE
Screenshot without background

### ISSUE THREAD

**Issue by ilias777** [NarutoXY/silicon.lua#12]
It's possible to save the screenshot without a background or with transparent background?

**Comment by NarutoXY** [comment]
Maybe try setting padHoriz and padVert to 0

**Comment by ilias777** [comment]
Unfortunately, no!! I tried with this settings and the result is the same.

**Comment by Slotos** [comment]
This kinda worked:
![image](https://user-images.githubusercontent.com/314453/200345524-295c5d67-c050-4ff2-87a9-28b268ded0c6.png)

```lua
  silicon.setup({
    padHoriz = 0,
    padVert = 0,
    bgColor = '#3330', -- RGBA, with A=0 it's transparent
    shadowBlurRadius = 0,
  })
```

You can even play with pad values to add transparent padding around the image:

![image](https://user-images.githubusercontent.com/314453/200345712-68afad29-a743-40c6-9606-1cf7f5188dbd.png)

**Comment by NarutoXY** [comment]
Closing this as @Slotos gave a solution. Thanks man for giving a solution.
