### ISSUE TITLE
Some error occured whie executing silicon

### ISSUE THREAD

**Issue by MiliAxe** [NarutoXY/silicon.lua#18]
## Description
I just updated my plugins after seeing the new feature of silicon.lua on reddit and now, silicon.lua doesn't seem to work anymore. (Using Arch Linux + Neovim v0.8.0)

## Steps done
Just after updating, this error occured
![image](https://user-images.githubusercontent.com/55515322/201030256-eeddb2d2-8deb-49ab-b63b-7dfe6042cda8.png)
So I just followed #9 and set the following variable:
![image](https://user-images.githubusercontent.com/55515322/201030733-1b4e39de-bf16-48f4-b723-d1ceb063da6d.png)
(pywal is the name of my colorscheme)

and after that, with the following config file:
![image](https://user-images.githubusercontent.com/55515322/201031992-db66c5ca-b39f-4963-9097-546744cb97fa.png)
when I try to use the keybinding that works in normal mode, I get the following error:
![image](https://user-images.githubusercontent.com/55515322/201032111-52a9338b-0e5a-4a66-89b0-bf0811934126.png)
and when I try to use the keybinding in visual mode, I get the following error:
![image](https://user-images.githubusercontent.com/55515322/201032188-64f4d3c6-ba1a-4462-9f09-3266d27f4788.png)

Also, the messages don't contain any specific debug message after setting `debug = true` as an argument.

By the way, the reason I used 
`silicon = require('silicon)` on top of my config, was because without it, this error would occur.
![image](https://user-images.githubusercontent.com/55515322/201033596-ead08754-feed-4edb-a99d-f9e83a46ecda.png)

**Edit:** trying to run the custom .tmTheme manually via command line results in this error:
![image](https://user-images.githubusercontent.com/55515322/201124323-cc01e9ed-6469-464a-a897-38e7307196fb.png)

Thanks for the great plugin

**Comment by NarutoXY** [comment]
Can you please provide the theme `.tmTheme` file. It should be somewhere in `.config/silicon/themes`

**Comment by DrKGD** [comment]
Now that you mention it, in an attempt I actually removed these files, thus I tried to recreate them though the API, precisely using
`require('silicon.utils').build_tmTheme()`, and it actually returns an usable error  

```
E5108: Error executing lua: ...k/packer/start/silicon.lua/lua/silicon/build_tmTheme.lua:17: bad argument #2 to 'format' (number expected, got nil)
stack traceback:
	[C]: in function 'format'
	...k/packer/start/silicon.lua/lua/silicon/build_tmTheme.lua:17: in function 'hl'
	...k/packer/start/silicon.lua/lua/silicon/build_tmTheme.lua:34: in function <...k/packer/start/silicon.lua/lua/silicon/build_tmTheme.lua:21>
	...site/pack/packer/start/silicon.lua/lua/silicon/utils.lua:67: in function 'build_tmTheme'
	...te/pack/packer/start/silicon.lua/lua/silicon/request.lua:72: in function 'exec'
	.../site/pack/packer/start/silicon.lua/lua/silicon/init.lua:46: in function 'visualise_api'
	/home/deatharte/.config/nvim/plugin/21-keys.lua:318: in function </home/deatharte/.config/nvim/plugin/21-keys.lua:317>
```

Pretty sure he's complaining about this line [build_tmTheme.lua](https://github.com/NarutoXY/silicon.lua/blob/main/lua/silicon/build_tmTheme.lua)
```lua
local color = string.format("#%x", hl[value])
```

Seems like there are two problems, or so I thought, with that statement
- Will probably hard-fail if the highlight group is missing, so probably should use a default case (and/or warn the user about it?)
- Not really sure that `#%x` always returns a valid hexadecimal color value, what about `#%06x` instead?

```lua
local color = string.format("#%06x", hl[value] or 0)
```

This is enough to make it work as expected: I am pretty sure the background color is the culprit, as I don't have one!
![image](https://user-images.githubusercontent.com/44092476/201248486-77c2e08e-15f7-4b07-b9dc-ff4657f85eb1.png)

<details> 
  <summary>In case I completly misunderstood the deal, here's the noctis.tmTheme you requested!</summary>
  
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>noctis</string>
	<key>settings</key>
	<array>
		<dict>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#000000</string>
				<key>foreground</key>
				<string>#fecedb</string>
				<key>lineHighlight</key>
				<string>#000000</string>
				<key>selection</key>
				<string>#64242e</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Comment</string>
			<key>scope</key>
			<string>comment</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#fd5d88</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>String</string>
			<key>scope</key>
			<string>string</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#66ffbf</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Number</string>
			<key>scope</key>
			<string>constant.numeric</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#3ddbd9</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Built-in constant</string>
			<key>scope</key>
			<string>constant.language</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#8cb6ff</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>User-defined constant</string>
			<key>scope</key>
			<string>constant.character, constant.other</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#fecedb</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Variable</string>
			<key>scope</key>
			<string>variable</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#33b1ff</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Keyword</string>
			<key>scope</key>
			<string>keyword</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#ff669c</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Storage</string>
			<key>scope</key>
			<string>storage</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#08bdba</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Storage type</string>
			<key>scope</key>
			<string>storage.type</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>italic</string>
				<key>foreground</key>
				<string>#08bdba</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Function name</string>
			<key>scope</key>
			<string>entity.name.function</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#00b4cc</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Function argument</string>
			<key>scope</key>
			<string>variable.parameter</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>italic</string>
				<key>foreground</key>
				<string>#33b1ff</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Tag name</string>
			<key>scope</key>
			<string>entity.name.tag</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#8cb6ff</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Tag attribute</string>
			<key>scope</key>
			<string>entity.other.attribute-name</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#8cb6ff</string>
			</dict>
		</dict>
	</array>
	<key>uuid</key>
	<string>D8D5E82E-3D5B-46B5-B38E-8C841C21347D</string>
	<key>colorSpaceName</key>
	<string>sRGB</string>
	<key>semanticClass</key>
	<string>theme.dark.noctis</string>
</dict>
</plist>
```
</details>

**Comment by DrKGD** [comment]
From my understanding

This should take a screenshot of the whole buffer, from top to bottom, not only the viewable part if it.
`:lua require('silicon').visualise_api({ to_clip = true, show_buf = true })`

With this you would achieve what are you trying to do (visible portion of buffer)
`:lua require('silicon').visualise_api({ to_clip = true, visible = true })`

Don't really know how to invoke this one without a keybinding, but you are always required to pass in a table, even an empty one, to the `visualise_api` function, so you either call this way `visualise_api{ }` or this other way `visualize_api({ })`, but `visualize_api()` is not accepted (yet).

For example the following would allow you to save a screenshot of the current selection
`vim.keymap.set('v', '<Leader>s',  function() silicon.visualise_api({ }) end )`

Can't really help you about the file's save location, it works just fine on my end with the default configuration: it produces a file in the current working directory
`:lua require('silicon').visualise_api({ show_buf = true })`

**Comment by MiliAxe** [comment]
Thanks for the comment, This still invokes an error for me unfortunately. 
I encounter `Some error occured while executing silicon`. I don't know if there are any logs or any way to see what is wrong under the hood.

**Comment by MiliAxe** [comment]
My issue has been solved with the latest version! Thanks for the great plugin.
