### ISSUE TITLE
Please expand the README

### ISSUE THREAD

**Issue by zeitchef** [NarutoXY/silicon.lua#3]
A bit more information would be appreciated in the README:

- is it necessary to have Rust and/or Silicon already installed?
- does this offer a command (eg. `:Silicon`) - or how to use the plugin?
- where is the default path the image is saved?

While I appreciate having a video, it should not replace documenting your work in the README. For me, the video controls cover the command in the command prompt, making it basically unreadable.

**Comment by NarutoXY** [comment]
Yes you need silicon to be installed, you can directly install binary and skip installing rust toolchain. 

Sadly, there's no :Silicon currently but is planned. 

I've posted the commands in reddit post. 

- Generate images of selected snippet.

```lua
require("silicon").visualise(false,false)
```

- Generate images of whole buffer with the selected snippet being highlighted by lighter background.

```lua
require("silicon").visualise(true,false)
```

- Copy the image of snippet to clipboard. (Only xclip is supported for Linux, Mac and windows are also supported)

```lua
require("silicon").visualise(false,true)
```


PS: First argument tells whether to show whole buffer content and second tells whether to copy to clipboard.

**Comment by NarutoXY** [comment]
Fixed with https://github.com/NarutoXY/silicon.lua/commit/e1902924d3600a7b1131a75efc7a638c7d7e1d39
