### ISSUE TITLE
"Some error occured while executing silicon"

### ISSUE THREAD

**Issue by EilifAkerjordet** [NarutoXY/silicon.lua#5]
I'm on Mac, nvim 0.8 and silicon v0.4.3.

Whenever I try to execute `lua require("silicon").visualise_api({})`, i get the error "some error ocurred while executing silicon" with no further information provided

**Comment by NarutoXY** [comment]
See #1

**Comment by EilifAkerjordet** [comment]
My bad! Thank you.
